version: "2"
services:
  mssql:
    image: microsoft/mssql-server-linux
    ports:      
       - 1433:1433
    environment:
       - ACCEPT_EULA=Y
       - SA_PASSWORD=!Passw0rd
    volumes:
       - /var/opt/mssql:/var/opt/mssql
       
#sudo docker run -e 'ACCEPT_EULA=Y' -e 'SA_PASSWORD=<YourStrong!Passw0rd>' -p 1433:1433 -v /var/opt/mssql:/var/opt/mssql -d microsoft/mssql-server-linux       